### ISSUE TITLE
Pluck-4.7.16dev1 admin background exists a remote command execution vulnerability when uploading files

### ISSUE THREAD

**Issue by k0xx11** [pluck-cms/pluck#106]
I uploaded any file in the "manage Files" section, where I uploaded "webshell.zip".
![image](https://user-images.githubusercontent.com/54017627/145823442-dd4cfcfe-3237-421f-8ea7-ae9238df0110.png)
Find the unzipped file in the upload folder
![image](https://user-images.githubusercontent.com/54017627/145823635-637815bf-d92c-4f70-b1f2-219c6dec8e9a.png)
![image](https://user-images.githubusercontent.com/54017627/145823720-bc66e9bf-83d1-4461-b924-bfd1980ddc50.png)

> The content in the 2.php file is "<? php phpinfo ();? >"

![image](https://user-images.githubusercontent.com/54017627/145823943-1ac28bc6-6d22-40e8-bfb2-c95543e5ab7a.png)
url: 192.168.1.128/pluck4.7.16dev1/data/modules/webshell/2.php
![image](https://user-images.githubusercontent.com/54017627/145824233-a70d5fd0-8ae9-4876-a07c-71d336cdf37b.png)

**Comment by BSteelooper** [comment]
I believe this is in the install modules section and not in the manage files section. 

A module is to add functionality to the website, and needs a password to do. When you have the password, you can upload anything, and than utilise this uploaded content. this is impossible to fix, since this is the option to add functionality. for instance the inplace updater is an module which downloads and extracts files, an other module might do the same, so why restrict this, and restrict it to what.

Since the password is needed to exploit this, and with the password lost everything is up for grabs we won't fix this.
