### ISSUE TITLE
There is arbitrary code execution and file containing in the module installation of 4.7.16-dev2

### ISSUE THREAD

**Issue by k0xx11** [pluck-cms/pluck#107]
php5.2.17
1.Arbitrary code execution
I uploaded webshell.zip in the module installation.
![image](https://user-images.githubusercontent.com/54017627/146119919-b7322b1f-679e-497f-bc8c-c13233447c4a.png)
![image](https://user-images.githubusercontent.com/54017627/146120002-d37a9afe-04a0-4e71-8cc7-54ec961dd3a5.png)

He will automatically extract it to "D:\ phpStudy\ PHPTutorial\ WWW\ pluck-4.7.16dev2\ data\ modules"
![image](https://user-images.githubusercontent.com/54017627/146120024-d917f048-2807-41e8-beec-d9d9219ba105.png)
![image](https://user-images.githubusercontent.com/54017627/146120043-60176e2f-f03f-4bc2-b5ba-9f0767cf3789.png)
Visit 192.168.1.128/pluck-4.7.16dev2/data/modules/webshell/webshell.php
![image](https://user-images.githubusercontent.com/54017627/146120621-cace9377-0428-4e55-b98f-1a99db4107b8.png)

2.The file contains vulnerabilities

After uploading the webshell.zip file in the module installation, I visit admin.php and he will automatically include the / data/modules/webshell/webshell.php file I uploaded.

![image](https://user-images.githubusercontent.com/54017627/146120665-2485b383-f8de-43c9-9bb9-eae22e81af10.png)
![image](https://user-images.githubusercontent.com/54017627/146120695-44d846e0-5a02-4896-ba30-a15f26c1e476.png)

**Comment by BSteelooper** [comment]
Duplicate for #106

I believe this is in the install modules section and not in the manage files section.

A module is to add functionality to the website, and needs a password to do. When you have the password, you can upload anything, and than utilise this uploaded content. this is impossible to fix, since this is the option to add functionality. for instance the inplace updater is an module which downloads and extracts files, an other module might do the same, so why restrict this, and restrict it to what.

Since the password is needed to exploit this, and with the password lost everything is up for grabs we won't fix this.

**Comment by BSteelooper** [comment]
It works as designed and is not a loophole. 
If it exists in the last version and we tell you it is as designed you don't have to make issues for all versions.. they are duplicates  at that moment. 


Ps. minimal supported php version is 7.0.

**Comment by k0xx11** [comment]
If it is the php7.0 version, there will be the same problem because you did not set the rule in "\ data\ modules\ .htaccess"

**Comment by k0xx11** [comment]
If you set the corresponding rule in "\ data\ modules\ .htaccess", it will be fixed. If you haven't set it up all the time, this vulnerability will exist all the time.

**Comment by k0xx11** [comment]
The vulnerability will only be fixed if you set the corresponding rules in "\ data\ modules\ .htaccess". If you haven't set it up all the time, then the vulnerability will always exist.

**Comment by k0xx11** [comment]
I am willing to test for the future version of your project, and I will not repeat the submission of issue this time. What do you think?

**Comment by BSteelooper** [comment]
When you have a module which has to have directly excecutable content such as a captcha this is not working with the .htaccess set. 
As this would limit the functionality of the modules section we designed it to allow executable code in the modules section. 

Since you need the password to install a module there is not really a security risk... with the  password you can do all kind of stuff.

**Comment by BSteelooper** [comment]
> I am willing to test for the future version of your project, and I will not repeat the submission of issue like this one. What do you think?

We welcome you testing Pluck. It can only become better.

**Comment by BSteelooper** [comment]
> The vulnerability will only be fixed if you set the corresponding rules in "\ data\ modules\ .htaccess". If you haven't set it up all the time, then the vulnerability will always exist.

When we do this, this would limit the functionality of the modules. 
If we don't include the allowoveride none you can simply include your own htaccess in the module to achieve this.

**Comment by k0xx11** [comment]
> We welcome you testing Pluck. It can only become better.

yes

**Comment by k0xx11** [comment]
> > 只有在"\ data\ modules\ .htaccess"中设置相应的规则时，才会修复此漏洞。如果您没有一直设置它，那么漏洞将始终存在。
> 
> 当我们这样做时，这将限制模块的功能。如果我们不包含 allowoveride，您可以简单地在模块中包含您自己的 htacces 来实现这一点。

yes
