### ISSUE TITLE
Arbitrary code execution and included files exist in the module installation of 4.7.16-dev3

### ISSUE THREAD

**Issue by k0xx11** [pluck-cms/pluck#108]
php5.2.17
1.Arbitrary code execution
I uploaded webshell.zip in the module installation.
![image](https://user-images.githubusercontent.com/54017627/146123511-913d21c9-f1d4-4dae-b85a-b8fa3e274295.png)
![image](https://user-images.githubusercontent.com/54017627/146123571-ce2c4e6a-595a-489d-a368-b42934be686f.png)
![image](https://user-images.githubusercontent.com/54017627/146123755-ebc68454-0f37-49dd-957c-7b3a2ff54ab7.png)
![image](https://user-images.githubusercontent.com/54017627/146123771-6d109ec2-148e-4972-b586-8f4d268d29e2.png)
Visit 192.168.1.128/pluck-4.7.16dev3/data/modules/webshell/webshell.php

![image](https://user-images.githubusercontent.com/54017627/146123882-da2fb3d8-bbff-42ee-ab45-db56597cf918.png)

2.The file contains vulnerabilities

After uploading the webshell.zip file in the module installation, I visit admin.php and he will automatically include the / data/modules/webshell/webshell.php file I uploaded.
After uploading the webshell.zip file successfully, it is found that http://192.168.1.128/pluck-4.7.16dev3/admin.php?action=managemodules automatically contains "D:\ phpStudy\ PHPTutorial\ WWW\ pluck-4.7.16dev3\ data\ modules\webshell\webshell.php".
![image](https://user-images.githubusercontent.com/54017627/146123706-d620b41c-3a66-48fb-a3e7-fdce9c9fa8c2.png)
![image](https://user-images.githubusercontent.com/54017627/146123843-546af442-c0c5-4ed5-8851-3d55e1d10bd8.png)
![image](https://user-images.githubusercontent.com/54017627/146123984-a1ee937b-51d3-4701-aef0-e0976e4b4f31.png)
![image](https://user-images.githubusercontent.com/54017627/146124031-bb2ce887-bb64-4e7b-b019-92f74cd7dbb0.png)

**Comment by BSteelooper** [comment]
Duplicate for #106

I believe this is in the install modules section and not in the manage files section.

A module is to add functionality to the website, and needs a password to do. When you have the password, you can upload anything, and than utilise this uploaded content. this is impossible to fix, since this is the option to add functionality. for instance the inplace updater is an module which downloads and extracts files, an other module might do the same, so why restrict this, and restrict it to what.

Since the password is needed to exploit this, and with the password lost everything is up for grabs we won't fix this.
