### ISSUE TITLE
XSS (Stored) in Pluck v4.7.7

### ISSUE THREAD

**Issue by security-provensec** [pluck-cms/pluck#64]
Affected software: Pluck v4.7.7
 
Type of vulnerability: XSS (Stored)
 
URL: https://www.pluck-cms.org 

Discovered by: Provensec

Website: https://www.provensec.com

Author: Balvinder Singh

Description: Stored attacks are those where the injected script is permanently stored on the target servers, such as in a database, in a message forum, visitor log, comment field, etc. The victim then retrieves the malicious script from the server when it requests the stored information. Stored XSS is also sometimes referred to as Persistent or Type-I XSS.

Proof of concept:
Step1: Login into the pluck CRM.
Step2: Edit the page title with the malicious script.
Vulnerable URL : http://localhost/pluck/pluck-4.7.7/admin.php?action=editpage&page=14253123
![pluckxss1_title_param](https://user-images.githubusercontent.com/41563984/44204403-0b223380-a170-11e8-821b-e254413426e9.JPG)

Step3: Here the XSS  get executed successfully.
URL Where XSS got executed: http://localhost/pluck/pluck-4.7.7/?file=default-aspx-img-src-x-onerror-prompt-0
![pluckxss2_title_param](https://user-images.githubusercontent.com/41563984/44204423-22612100-a170-11e8-8d05-53f915f5daba.JPG)

**Comment by BSteelooper** [comment]
I have modified the Sanitize function to resolve this. Can you verify?

**Comment by security-provensec** [comment]
Is this patch in the current version?

**Comment by BSteelooper** [comment]
[pluck-4.7.8-dev1.tar.gz](https://github.com/pluck-cms/pluck/files/2293477/pluck-4.7.8-dev1.tar.gz)

**Comment by BSteelooper** [comment]
It is in this version

**Comment by security-provensec** [comment]
Yes, we confirm that xss has been patched from your side.

**Comment by security-provensec** [comment]
Hi,

Thanks for your positive response,

Did you use CVE ID to track these bugs?

Looking forward to hearing from you.

**Comment by BSteelooper** [comment]
Hello,

We use Github to track bugs.

I didn't log an CVE, and I will not, the security researcher is the one requesting and maintaining the CVE, not the developer. 

In this case **this is not a security bug** in the sense that **the password is required (Or being logged on)** before this is exploitable. After having the password everything is modifiable otherwise logging in is not needed.
**The admin part after being logged in is assumed trusted**, and therefor all changes are trusted. 
When no password (being logged in) is required this would qualify as a security bug. 

In this particular case we modified the page to prevent tags as an additional feature to prevent legitimate users from performing this task.

Regards,

Bas

**Comment by BSteelooper** [comment]
This is an invalid report. With the password the complete website can be taken over. Without the password this is not exploitable.
